---
abstract: 'Alternative, condensed format for JSON Schemas'
author:
  - 'Yanick Champoux <yanick@babyl.dyndns.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  JSON: '0'
  Test::Deep: '0'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.043, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: JSON-Schema-Shorthand
provides:
  JSON::Schema::Shorthand:
    file: lib/JSON/Schema/Shorthand.pm
    version: v0.0.1
requires:
  Clone: '0'
  Exporter::Tiny: '0'
  experimental: '0'
  parent: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/yanick/perl-JSON-Schema-Shorthand/issues
  homepage: https://github.com/yanick/perl-JSON-Schema-Shorthand
  repository: https://github.com/yanick/perl-JSON-Schema-Shorthand.git
version: 0.0.1
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
x_contributors:
  - 'Yanick Champoux <yanick@cpan.org>'
